Fix missing-prototypes
verve.c:91:1: error: no previous prototype for 'verve_command_callback' [-Werror=missing-prototypes]
verve-plugin.c:92:1: error: no previous prototype for 'verve_plugin_load_completion' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>